import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import { getFirestore, doc, onSnapshot, setDoc, updateDoc, collection, query, where, getDocs, writeBatch, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';
const db=getFirestore(initializeApp(firebaseConfig)), q=id=>document.getElementById(id); let currentSession=q('sessionInput').value.trim(),unsub=null;
const sessionRef=()=>doc(db,'sessions',currentSession); const options=()=>q('optionsInput').value.split('\n').map(x=>x.trim()).filter(Boolean);
function typeUI(){q('optionsWrap').style.display=q('typeInput').value==='choice'?'block':'none'} q('typeInput').onchange=typeUI; typeUI();
function subscribe(){if(unsub)unsub();unsub=onSnapshot(sessionRef(),async snap=>{if(!snap.exists())return render(null,[]);const d=snap.data();q('questionInput').value=d.question||'';q('typeInput').value=d.type||'choice';typeUI();if(d.options?.length)q('optionsInput').value=d.options.join('\n');q('showResults').checked=!!d.showResults;if(d.type==='wordcloud')await loadWords(d.roundId);else render(d,[])});updateUrl()}
q('sessionInput').onchange=()=>{currentSession=q('sessionInput').value.trim()||'processo-ai-2026';subscribe()};
async function save(open=false){const type=q('typeInput').value,opts=type==='choice'?options():[];await setDoc(sessionRef(),{question:q('questionInput').value.trim(),type,options:opts,counts:opts.map(()=>0),isOpen:open,showResults:q('showResults').checked,roundId:crypto.randomUUID(),updatedAt:serverTimestamp()},{merge:true})}
q('saveBtn').onclick=()=>save(false);q('openBtn').onclick=()=>save(true);q('closeBtn').onclick=()=>updateDoc(sessionRef(),{isOpen:false,updatedAt:serverTimestamp()});q('showResults').onchange=()=>updateDoc(sessionRef(),{showResults:q('showResults').checked,updatedAt:serverTimestamp()});
q('resetBtn').onclick=async()=>{const snap=await getDocs(query(collection(db,'responses'),where('sessionId','==',currentSession)));const b=writeBatch(db);snap.forEach(x=>b.delete(x.ref));await b.commit();const opts=options();await updateDoc(sessionRef(),{counts:opts.map(()=>0),roundId:crypto.randomUUID(),updatedAt:serverTimestamp()})};
async function loadWords(roundId){if(!roundId)return render(null,[]);const snap=await getDocs(query(collection(db,'responses'),where('sessionId','==',currentSession),where('roundId','==',roundId)));render({type:'wordcloud'},snap.docs.map(x=>x.data().text||''))}
function render(d,words){if(d?.type==='wordcloud'){const freq={};words.forEach(w=>{const k=w.trim().toLocaleLowerCase('it');if(k)freq[k]=(freq[k]||0)+1});const arr=Object.entries(freq).sort((a,b)=>b[1]-a[1]);q('totalVotes').textContent=words.length;q('results').innerHTML=`<div class="cloud">${arr.map(([w,n])=>`<span style="font-size:${Math.min(52,18+n*7)}px" title="${n}">${esc(w)}</span>`).join('')}</div>`;return}const counts=d?.counts||[],opts=d?.options||[],total=counts.reduce((a,b)=>a+b,0);q('totalVotes').textContent=total;q('results').innerHTML=opts.map((o,i)=>{const n=counts[i]||0,p=total?Math.round(n*100/total):0;return `<div class="result-row"><div><strong>${esc(o)}</strong><span>${n} voti · ${p}%</span></div><div class="bar"><i style="width:${p}%"></i></div></div>`}).join('')}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function updateUrl(){const base=location.href.replace(/admin\.html.*$/,'index.html');q('participantUrl').textContent=`${base}?s=${encodeURIComponent(currentSession)}`}subscribe();
